### ISSUE TITLE
load添加了旋转动画   不执行

### ISSUE THREAD

**Issue by xiang473535976** [lijiee/harmony_base#1]
animateTo({
        duration: 72 * 3 * 1000, //动画时长
        curve: Curve.Linear, //动画匀速
        iterations: 100, //动画次数
        playMode: PlayMode.Alternate, //来回交替
      }, () => {
        this.angle = 720 * 1000
      })

具体代码看附件  谢谢

[LoadDialog.zip](https://github.com/lijiee/harmony_base/files/15144531/LoadDialog.zip)

**Comment by xiang473535976** [comment]
直接用页面打开，动画直接，用大佬的loading窗口打开     就不执行动画了

**Comment by lijiee** [comment]
我看的是可以的啊

https://github.com/lijiee/harmony_base/assets/17916798/184cc42f-6770-4ca3-8bee-3ca3bb485c36

**Comment by xiang473535976** [comment]
我再试一试 谢谢
